### ISSUE TITLE
[Request] use a versioning system for the robot models

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [google-deepmind/mujoco_menagerie#35]
From what I can tell, some models like the [shadowhand](https://github.com/google-deepmind/mujoco_menagerie/blob/main/shadow_hand/README.md) have been changed without any versioning indication of such a change, it would be important for reproducibility to include a versioning system for new changes.

Here is a proposal for versioning system

changes that do not modify the behavior of the model like "[Cleanup XML files](https://github.com/google-deepmind/mujoco_menagerie/commit/c5d2e83f49a2a1201153a686de0d26cc02b3bd98)" should not require a new version

## simple versioning system
- `*-v0`
- `*-v1`
- `*-v2`
- `*-v3`
(good for infrequent changes)

## semantic versioning system
- `*-v0.0.0`
- `*-v1.0.0`
- `*-v1.0.1`
- `*-v1.0.2`
- `*-v1.0.3`
- `*-v1.1.0`

in either case, the README of each model should indicate the changes in a `# version history` section

Note: technically, it is not a requirement for all the environments to use the same versioning system. But it would be preferable 
Note: for existing models, you can keep the name but update it with a versioning system when an update is made 

Thanks!

**Comment by kevinzakka** [comment]
If you are worried about changes in Menagerie breaking upstream code, then I would recommend you pin the repo to a specific commit number. Otherwise, I am thinking of adding a `CHANGELOG.md` in each robot directory denoting the changes made at each commit. And I'll try to get version and release tags for each robot submitted on a more regular basis.
